com:
  book:
    name: dev-good bye
    page: 111
#mysql 连接配置
spring:
  datasource:
    url: jdbc:mysql://192.168.160.7:8066/TESTDB
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#redis
  redis:
    host: 192.168.160.7
    port: 6379
    #password:
    #redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 1000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      #max-wait: -1
      # 连接池中的最大空闲连接
      #max-idle: 500
      # 连接池中的最小空闲连接
      #min-idle: 0

